### ISSUE TITLE
getAccountbalance() returns data table listing with column metadata

### ISSUE THREAD

**Issue by nuclearspike** [Nexosis/nexosisclient-js#2]
Calling the getAccountbalance() on the client returns the following:

{ items: [ { dataSetName: 'myDataset', columns: [Object] } ] }

I was expecting to have it show how much money is remaining.

**Comment by jeffesp** [comment]
Hey @nuclearspike, thanks for the bug report. We have a fix for this that should be out soon.

**Comment by jeffesp** [comment]
Fixed in version 1.0.2, and published to NPM.
